### Get all workouts
GET http://localhost:3001/api/workouts

###

### Get single workout
GET http://localhost:3001/api/workouts/1

###

### Create a new workout
POST http://localhost:3001/api/workouts
Content-Type: application/json

{
  "name": "Hauiskääntö",
  "sets": 3,
  "reps": 12,
  "weight": 25,
  "date": "2024-01-17"
}

###

### Update workout
PUT http://localhost:3001/api/workouts/1
Content-Type: application/json

{
  "name": "Penkkipunnerrus (päivitetty)",
  "sets": 4,
  "reps": 8,
  "weight": 85
}

###

### Delete workout
DELETE http://localhost:3001/api/workouts/3

###

### Health check
GET http://localhost:3001/health